# scrutinizer-ci.com configuration
imports:
  - php
filter:
  excluded_paths:
    - build/
    - tmp/
    - vendor/
    - doctum-config.php
checks:
  php: true
tools:
  external_code_coverage:
    runs: 14 # for all matrix PHP versions to upload
    timeout: 480 # 8 min
build:
  nodes:
    analysis:
      environment:
        php: 8.2
      dependencies:
        before:
          - composer install
      tests:
        override:
          - php-scrutinizer-run
          -
            command: phpcs-run
            use_website_config: false
