language: php

dist: xenial

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
  include:
    - php: 7.1
      env: DOCS=yes

sudo: false

install:
  - composer install

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.composer/cache

script:
  - ./vendor/bin/phpunit --configuration phpunit.xml.dist
  - if [ "$DOCS" = "yes" ] ; then ./vendor/bin/sami.php --no-interaction update ./sami-config.php ; fi
