name: Lint PHP documentation

on:
  push:
  pull_request:

jobs:
    lint-docs:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Lint PHP documentation
              uses: sudo-bot/action-doctum@v5
              with:
                  config-file: doctum-config.php
                  method: "parse"
                  cli-args: "--output-format=github --no-ansi --no-progress -v --ignore-parse-errors"
